const SETTINGS_PANEL_WIDTH = 60;
const SIDEBAR_MAX_WIDTH = 250 + SETTINGS_PANEL_WIDTH;
const MAIN_CONTENT_INNER_WIDTH = 600

export const DIMENSIONS = {
    SETTINGS_PANEL_WIDTH,
    SIDEBAR_MAX_WIDTH,
    MAIN_CONTENT_INNER_WIDTH
}
export const DIMENSIONS_COMPUTED = {
}
