const SETTINGS_PANEL_WIDTH = 60;
const SIDEBAR_NAVPANEL_WIDTH = 300
const SIDEBAR_MAX_WIDTH = SIDEBAR_NAVPANEL_WIDTH + SETTINGS_PANEL_WIDTH;
const MAIN_CONTENT_INNER_WIDTH = 600

export const DIMENSIONS = {
    SETTINGS_PANEL_WIDTH,
    NAVPANEL_WIDTH: SIDEBAR_NAVPANEL_WIDTH,
    SIDEBAR_MAX_WIDTH,
    MAIN_CONTENT_INNER_WIDTH
}
export const DIMENSIONS_COMPUTED = {
}
